# Generated by Django 5.1.1 on 2024-10-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialclient',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
