# Generated by Django 5.1.1 on 2025-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_sellers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_profit_by_brands',
            field=models.BooleanField(default=False),
        ),
    ]
