# Generated by Django 5.1.1 on 2025-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
