# Generated by Django 5.1.1 on 2025-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_has_sellers_tenant_show_profit_by_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_stock_in_storages',
            field=models.BooleanField(default=False),
        ),
    ]
