# Generated by Django 5.1.1 on 2025-01-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_payment_months_alter_payment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='short_name',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
