# Generated by Django 5.1.1 on 2025-03-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_show_stock_in_storages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='has_sellers',
            new_name='displays_stock_in_storages',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='show_profit_by_brands',
            new_name='supports_departments',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='show_stock_in_storages',
        ),
        migrations.AddField(
            model_name='tenant',
            name='sellers',
            field=models.IntegerField(default=0),
        ),
    ]
