# Generated by Django 5.1.1 on 2025-01-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='short_name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
