# Generated by Django 5.1.1 on 2025-05-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_rename_has_sellers_tenant_displays_stock_in_storages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='supports_reservations',
            field=models.BooleanField(default=False),
        ),
    ]
