# Generated by Django 5.1.1 on 2025-01-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='short_name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
