# Generated by Django 5.1.1 on 2025-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_supports_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accepts_exchanges',
            field=models.BooleanField(default=False),
        ),
    ]
