# Generated by Django 5.1.1 on 2026-03-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_accepts_exchanges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='accepts_exchanges',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='sellers',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='supports_departments',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='supports_reservations',
        ),
    ]
