# Generated by Django 5.1.1 on 2025-01-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenant_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='stores',
            field=models.IntegerField(),
        ),
    ]
