# Generated by Django 5.1.1 on 2026-04-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_remove_tenant_accepts_exchanges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='create_products_on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
