# Generated by Django 5.1.1 on 2026-05-14 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_create_products_on_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stores', models.IntegerField()),
                ('storages', models.IntegerField()),
                ('billing_type', models.CharField(choices=[('S', 'Suscripción'), ('M', 'Manual')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.plan'),
        ),
    ]
