# Generated by Django 5.1.1 on 2026-05-31 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_plan_tenant_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='storages',
        ),
        migrations.AddField(
            model_name='plan',
            name='mp_plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mp_subscription_id', models.CharField(max_length=100, unique=True)),
                ('payer_email', models.EmailField(max_length=254)),
                ('external_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('authorized', 'Autorizada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mp_payment_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
