# Generated by Django 5.1.1 on 2026-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_remove_plan_storages_plan_mp_plan_id_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
