# Generated by Django 5.1.1 on 2026-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_plan_is_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card_token_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method_id',
            field=models.CharField(default='credit_card', max_length=50),
        ),
    ]
