# Generated by Django 5.1.1 on 2026-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_subscription_card_token_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card_token_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='active', max_length=20),
        ),
    ]
