# Generated by Django 5.1.1 on 2026-06-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_remove_subscription_external_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='card_token_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
