# Generated by Django 5.1.1 on 2026-06-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_subscription_card_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mp_external_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
