# Generated by Django 5.1.1 on 2026-07-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_payment_mp_external_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
