# Generated by Django 5.1.1 on 2026-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_alter_tenant_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('price', 'Precio'), ('not_using', 'No lo uso'), ('switched_tool', 'Cambié de herramienta'), ('missing_features', 'Faltan funciones'), ('technical_issues', 'Problemas técnicos'), ('business_closed', 'Cerró el negocio'), ('other', 'Otro')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('authorized', 'Autorizada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='authorized', max_length=20),
        ),
    ]
