# Generated by Django 5.1.1 on 2026-09-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_subscription_card_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='no_payment_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
