# Generated by Django 5.1.1 on 2025-01-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_discount_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('discount__tenant', models.F('discount__tenant'))), fields=('phone_number',), name='unique_tenant_phone_number'),
        ),
    ]
