# Generated by Django 5.1.1 on 2024-11-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_discount_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
