# Generated by Django 5.1.1 on 2025-01-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_tenant_phone_number',
        ),
    ]
