# Generated by Django 5.1.1 on 2025-05-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
        ('products', '0026_delete_storeproductlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='store',
        ),
        migrations.AddField(
            model_name='printer',
            name='has_cut_command',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='version_code',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='StorePrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10)),
                ('version_code', models.IntegerField(default=1)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer', to='products.store')),
            ],
        ),
    ]
