# Generated by Django 5.1.1 on 2025-05-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_remove_printer_store_printer_has_cut_command_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorePrinter',
        ),
    ]
