# Generated by Django 5.1.1 on 2025-05-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_delete_storeprinter'),
        ('products', '0026_delete_storeproductlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='printers.printer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer', to='products.store')),
            ],
        ),
    ]
