# Generated by Django 5.1.1 on 2025-07-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_storeprinter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='has_cut_command',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='version_code',
        ),
        migrations.AddField(
            model_name='printer',
            name='fort_height',
            field=models.IntegerField(default=20),
        ),
    ]
