# Generated by Django 5.1.1 on 2025-07-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0005_remove_printer_has_cut_command_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='fort_height',
            new_name='font_height',
        ),
    ]
