# Generated by Django 5.1.1 on 2025-04-17 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0026_delete_storeproductlog'),
        ('sales', '0005_rename_saler_sale_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_stock', models.IntegerField()),
                ('updated_stock', models.IntegerField()),
                ('action', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('A', 'Ajuste')], max_length=1)),
                ('movement', models.CharField(choices=[('MA', 'Manual'), ('IM', 'Importación'), ('DI', 'Distribución'), ('TR', 'Transferencia'), ('DE', 'Devolucíon'), ('VE', 'Venta')], default='MA', max_length=2)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product_logs', to='products.storeproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
