# Generated by Django 5.1.1 on 2025-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_storeproductlog_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='action',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('A', 'Ajuste'), ('N', 'Ninguno')], max_length=1),
        ),
        migrations.AlterField(
            model_name='storeproductlog',
            name='movement',
            field=models.CharField(choices=[('MA', 'Manual'), ('IM', 'Importación'), ('DI', 'Distribución'), ('TR', 'Transferencia'), ('DE', 'Devolucíon'), ('VE', 'Venta'), ('AP', 'Apartado')], default='MA', max_length=2),
        ),
    ]
