# Generated by Django 5.1.1 on 2025-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_storeproductlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='action',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('A', 'Ajuste'), ('N', 'NA')], max_length=1),
        ),
    ]
