# Generated by Django 5.1.1 on 2025-08-20 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_storeproductlog_action'),
        ('products', '0027_remove_store_has_printer_installed_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductlog',
            name='store_product_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_product_related_logs', to='products.storeproduct'),
        ),
    ]
