# Generated by Django 5.1.1 on 2025-08-20 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_storeproductlog_store_product_related'),
        ('products', '0027_remove_store_has_printer_installed_store_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductlog',
            name='store_product_related',
        ),
        migrations.AddField(
            model_name='storeproductlog',
            name='store_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_related', to='products.store'),
        ),
    ]
