# Generated by Django 5.1.1 on 2026-03-04 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_remove_storeproductlog_store_product_related_and_more'),
        ('products', '0033_add_performance_indexes_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storeproductlog',
            index=models.Index(fields=['store_product', 'created_at'], name='logs_storep_store_p_170f09_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductlog',
            index=models.Index(fields=['user', 'created_at'], name='logs_storep_user_id_22e260_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductlog',
            index=models.Index(fields=['action', 'movement', 'created_at'], name='logs_storep_action_a99ff9_idx'),
        ),
    ]
