# Generated by Django 5.1.1 on 2026-03-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_add_performance_indexes_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='movement',
            field=models.CharField(choices=[('MA', 'Manual'), ('IM', 'Importación'), ('DI', 'Distribución'), ('TR', 'Transferencia'), ('DE', 'Devolución'), ('VE', 'Venta'), ('AP', 'Apartado')], default='MA', max_length=2),
        ),
    ]
