# Generated by Django 5.1.1 on 2026-04-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_productpricelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricelog',
            name='field',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productpricelog',
            name='new_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productpricelog',
            name='previous_value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
