# Generated by Django 5.1.1 on 2026-08-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_alter_productpricelog_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='movement',
            field=models.CharField(choices=[('MA', 'Manual'), ('IM', 'Importación'), ('DI', 'Distribución'), ('TR', 'Transferencia'), ('DE', 'Devolución'), ('VE', 'Venta'), ('AP', 'Apartado'), ('CO', 'Conversión')], default='MA', max_length=2),
        ),
    ]
