# Generated by Django 5.1.1 on 2026-08-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_storeproductlog_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='previous_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storeproductlog',
            name='updated_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
