# Generated by Django 5.1.1 on 2025-02-23 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_delete_printer'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('USB', 'USB'), ('WIFI', 'WIFI')], max_length=4)),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.store')),
            ],
        ),
    ]
