# Generated by Django 5.1.1 on 2025-02-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_printer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
