# Generated by Django 5.1.1 on 2025-01-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_saler_sale_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='store',
        ),
    ]
