# Generated by Django 5.1.1 on 2025-03-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_payment_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='saler',
            new_name='seller',
        ),
    ]
