# Generated by Django 5.1.1 on 2025-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_saler_sale_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
