# Generated by Django 5.1.1 on 2024-10-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_client_payment_saleproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total',
            new_name='amount',
        ),
    ]
