# Generated by Django 5.1.1 on 2025-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='returned_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
