# Generated by Django 5.1.1 on 2024-10-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_total_sale_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='amount',
            new_name='total',
        ),
    ]
