# Generated by Django 5.1.1 on 2024-10-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_amount_sale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale'),
        ),
    ]
