# Generated by Django 5.1.1 on 2025-04-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_productsale_returned_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_canceled',
        ),
    ]
