# Generated by Django 5.1.1 on 2025-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_sale_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reservation_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
