# Generated by Django 5.1.1 on 2024-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_payment_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('PT', 'Pago con tarjeta'), ('TR', 'Transferencia')], max_length=2),
        ),
    ]
