# Generated by Django 5.1.1 on 2025-01-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_productsale_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_product', to='sales.sale'),
        ),
    ]
