# Generated by Django 5.1.1 on 2025-05-08 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_productsale_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
