# Generated by Django 5.1.1 on 2025-08-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_sale_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reason_cancel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
