# Generated by Django 5.1.1 on 2025-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_sale_saler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TA', 'Tarjeta'), ('TR', 'Transferencia')], max_length=2),
        ),
    ]
