# Generated by Django 5.1.1 on 2026-03-04 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0033_add_performance_indexes_v2'),
        ('sales', '0014_sale_reason_cancel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'created_at', 'reservation_in_progress'], name='sales_sale_store_i_b897dc_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'seller', 'created_at'], name='sales_sale_store_i_30484d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['client', 'created_at'], name='sales_sale_client__1a4c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_canceled', 'created_at'], name='sales_sale_is_canc_d78bf8_idx'),
        ),
    ]
