# Generated by Django 5.1.1 on 2026-03-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_add_performance_indexes_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='has_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='reason_return',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
