# Generated by Django 5.1.1 on 2026-03-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_sale_has_return_sale_reason_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='returned_quantity',
        ),
    ]
