# Generated by Django 5.1.1 on 2026-08-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_remove_productsale_returned_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_reservation_payment',
            field=models.BooleanField(default=False),
        ),
    ]
