# Generated by Django 5.1.1 on 2026-08-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_payment_is_reservation_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_reservation_payment',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('A', 'Apartado'), ('V', 'Venta')], default='V', max_length=12),
        ),
    ]
