# Generated by Django 5.1.1 on 2026-08-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_remove_payment_is_reservation_payment_sale_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
