# Generated by Django 5.1.1 on 2025-01-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='apply_wholesale_price_on_costumer_discount',
            new_name='apply_wholesale_price_on_customer_discount',
        ),
    ]
