# Generated by Django 5.1.1 on 2024-10-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeproduct',
            old_name='quantity',
            new_name='stock',
        ),
    ]
