# Generated by Django 5.1.1 on 2025-01-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='store_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product_logs', to='products.storeproduct'),
        ),
    ]
