# Generated by Django 5.1.1 on 2024-10-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_quantity_storeproduct_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='public_sale_price',
            new_name='unit_sale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='min_wholesale_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
