# Generated by Django 5.1.1 on 2025-01-22 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_apply_wholesale_price_on_customer_discount_product_apply_wholesale_price_on_client_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StoreProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_quantity', models.IntegerField()),
                ('updated_quantity', models.IntegerField()),
                ('action', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('A', 'Ajuste')], max_length=1)),
                ('movement', models.CharField(blank=True, choices=[('D', 'Distribucion'), ('T', 'Transferencia'), ('C', 'Cancelación de compra'), ('V', 'Venta')], max_length=1, null=True)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.storeproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
