# Generated by Django 5.1.1 on 2025-01-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_store_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_wholesale_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
