# Generated by Django 5.1.1 on 2024-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_public_sale_price_product_unit_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('A', 'Almacen'), ('T', 'Tienda')], default='A', max_length=1),
        ),
    ]
