# Generated by Django 5.1.1 on 2025-01-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_storeproductlog_store_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeproductlog',
            old_name='previous_quantity',
            new_name='previous_stock',
        ),
        migrations.RenameField(
            model_name='storeproductlog',
            old_name='updated_quantity',
            new_name='updated_stock',
        ),
    ]
