# Generated by Django 5.1.1 on 2024-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_store_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('A', 'Almacen'), ('T', 'Tienda')], max_length=1),
        ),
    ]
