# Generated by Django 5.1.1 on 2025-01-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_previous_quantity_storeproductlog_previous_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='movement',
            field=models.CharField(blank=True, choices=[('D', 'Distribución'), ('T', 'Transferencia'), ('C', 'Devolucíon'), ('V', 'Venta')], max_length=1, null=True),
        ),
    ]
