# Generated by Django 5.1.1 on 2025-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand__tenant', 'code'), name='unique_tenant_code_product'),
        ),
    ]
