# Generated by Django 5.1.1 on 2025-01-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_storeproductlog_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='movement',
            field=models.CharField(choices=[('DI', 'Distribución'), ('TR', 'Transferencia'), ('DE', 'Devolucíon'), ('VE', 'Venta'), ('MA', 'Manual')], default='MA', max_length=2),
        ),
    ]
