# Generated by Django 5.1.1 on 2025-01-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_storeproductlog_movement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purchase_price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_sale_price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wholesale_sale_price',
            new_name='wholesale_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='apply_wholesale_price_on_client_discount',
            new_name='wholesale_price_on_client_discount',
        ),
    ]
