# Generated by Django 5.1.1 on 2024-10-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
