# Generated by Django 5.1.1 on 2025-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_purchase_price_product_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='printer_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
    ]
