# Generated by Django 5.1.1 on 2025-01-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_unique_tenant_code_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_tenant_code_product',
        ),
    ]
