# Generated by Django 5.1.1 on 2024-10-29 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='products.store')),
                ('origin_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='products.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
