# Generated by Django 5.1.1 on 2024-11-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_producttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransfer',
            name='transfer_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
