# Generated by Django 5.1.1 on 2025-02-04 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_store_printer_ip_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.store'),
        ),
    ]
