# Generated by Django 5.1.1 on 2024-11-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_producttransfer_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apply_wholesale_price_on_costumer_discount',
            field=models.BooleanField(default=False),
        ),
    ]
