# Generated by Django 5.1.1 on 2025-02-05 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_connection_printer_connection_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
