# Generated by Django 5.1.1 on 2025-02-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_cashflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.store'),
        ),
    ]
