# Generated by Django 5.1.1 on 2025-02-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_storeproduct_product_alter_storeproduct_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
