# Generated by Django 5.1.1 on 2025-02-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_delete_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_printer_installed',
            field=models.BooleanField(default=False),
        ),
    ]
