# Generated by Django 5.1.1 on 2025-03-07 13:14

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_store_has_printer_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.Product.path),
        ),
    ]
