# Generated by Django 5.1.1 on 2025-03-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_storeworker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeworker',
            old_name='user',
            new_name='worker',
        ),
        migrations.AlterField(
            model_name='storeworker',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='products.store'),
        ),
    ]
