# Generated by Django 5.1.1 on 2025-03-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='movement',
            field=models.CharField(choices=[('DI', 'Distribución'), ('TR', 'Transferencia'), ('DE', 'Devolucíon'), ('VE', 'Venta'), ('MA', 'Manual'), ('EX', 'Excel')], default='MA', max_length=2),
        ),
    ]
