# Generated by Django 5.1.1 on 2025-03-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_storeproductlog_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductlog',
            name='movement',
            field=models.CharField(choices=[('DI', 'Distribución'), ('TR', 'Transferencia'), ('DE', 'Devolucíon'), ('VE', 'Venta'), ('MA', 'Manual'), ('IM', 'Importación')], default='MA', max_length=2),
        ),
    ]
