# Generated by Django 5.1.1 on 2025-04-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_storeproductlog_movement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreProductLog',
        ),
    ]
