# Generated by Django 5.1.1 on 2025-06-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_delete_storeproductlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='has_printer_installed',
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
