# Generated by Django 5.1.1 on 2025-09-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_store_has_printer_installed_store_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['store', 'product'], name='products_st_store_i_011e29_idx'),
        ),
    ]
