# Generated by Django 5.1.1 on 2025-09-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code', 'brand'], name='products_pr_code_f9076b_idx'),
        ),
    ]
