# Generated by Django 5.1.1 on 2025-11-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_datetime', models.DateTimeField(blank=True, null=True)),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions_to', to='products.store')),
                ('origin_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions_from', to='products.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='products.distribution'),
        ),
    ]
