# Generated by Django 5.1.1 on 2026-03-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_distribution_transfer_distribution'),
        ('tenants', '0006_tenant_accepts_exchanges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant', 'name'], name='products_br_tenant__b78016_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'name'], name='products_de_tenant__38bc09_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'name'], name='products_pr_brand_i_b721bc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'department'], name='products_pr_brand_i_5cf291_idx'),
        ),
    ]
