# Generated by Django 5.1.1 on 2026-03-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_add_performance_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_non_negative'),
        ),
    ]
