# Generated by Django 5.1.1 on 2026-03-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_add_stock_validation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['origin_store', 'transfer_datetime'], name='products_tr_origin__62db12_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['destination_store', 'transfer_datetime'], name='products_tr_destina_cc097c_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['product', 'origin_store', 'transfer_datetime'], name='products_tr_product_fe62bc_idx'),
        ),
    ]
