# Generated by Django 5.1.1 on 2026-03-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_add_trigram_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='brand_name_trgm',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_name_trgm',
        ),
    ]
