# Generated by Django 5.1.1 on 2026-03-25 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_brand_brand_name_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_stock', models.IntegerField()),
                ('applied', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to=settings.AUTH_USER_MODEL)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='products.storeproduct')),
            ],
            options={
                'indexes': [models.Index(fields=['applied', 'created_at'], name='products_st_applied_75fc37_idx')],
            },
        ),
    ]
