# Generated by Django 5.1.1 on 2026-03-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_stockupdaterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockupdaterequest',
            old_name='updated_stock',
            new_name='requested_stock',
        ),
    ]
