# Generated by Django 5.1.1 on 2026-04-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_rename_updated_stock_stockupdaterequest_requested_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='requires_stock_verification',
            field=models.BooleanField(default=False),
        ),
    ]
