# Generated by Django 5.1.1 on 2026-04-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_storeproduct_requires_stock_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
