# Generated by Django 5.1.1 on 2026-08-17 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('source_unit', models.CharField(choices=[('PZ', 'Pieza'), ('KG', 'Kilogramo'), ('CO', 'Costal'), ('LT', 'Litro'), ('MT', 'Metro'), ('RL', 'Rollo'), ('CJ', 'Caja')], max_length=2)),
                ('target_unit', models.CharField(choices=[('PZ', 'Pieza'), ('KG', 'Kilogramo'), ('CO', 'Costal'), ('LT', 'Litro'), ('MT', 'Metro'), ('RL', 'Rollo'), ('CJ', 'Caja')], max_length=2)),
                ('source_store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='products.storeproduct')),
                ('target_store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='products.storeproduct')),
            ],
        ),
    ]
