# Generated by Django 5.1.1 on 2026-08-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_storeproductconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductconversion',
            name='factor',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
