# Generated by Django 5.1.1 on 2026-08-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_storeproductconversion_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(default=10)),
                ('source_unit', models.CharField(choices=[('PZ', 'Pieza'), ('KG', 'Kilogramo'), ('CO', 'Costal'), ('LT', 'Litro'), ('MT', 'Metro'), ('RL', 'Rollo'), ('CJ', 'Caja')], max_length=2)),
                ('target_unit', models.CharField(choices=[('PZ', 'Pieza'), ('KG', 'Kilogramo'), ('CO', 'Costal'), ('LT', 'Litro'), ('MT', 'Metro'), ('RL', 'Rollo'), ('CJ', 'Caja')], max_length=2)),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='products.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='StoreProductConversion',
        ),
    ]
