# Generated by Django 5.1.1 on 2026-08-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_productconversion_delete_storeproductconversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconversion',
            name='source_unit',
        ),
        migrations.RemoveField(
            model_name='productconversion',
            name='target_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='sells_by_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('PZ', 'Pieza'), ('KG', 'Kilogramo'), ('CO', 'Costal')], default='PZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='stockupdaterequest',
            name='requested_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
