# Generated by Django 5.1.1 on 2026-08-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_remove_productconversion_source_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sells_by_weight',
        ),
    ]
