# Generated by Django 5.1.1 on 2026-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_remove_product_sells_by_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('PZ', 'Pieza'), ('KG', 'Kilogramo'), ('LT', 'Litro'), ('BO', 'Bote'), ('CO', 'Costal')], default='PZ', max_length=2),
        ),
    ]
